steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['-P jar-with-dependencies', 'package', 'appengine:deploy']
    env: ['-Dspring-boot.run.arguments= --discord.token=$$DISCORDTOKEN"']
    secretEnv: ['DISCORDTOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/mystic-column-275402/secrets/discord-token/versions/latest
        env: 'DISCORDTOKEN'