runtime: java8
api_version: user_defined
env: standard
threadsafe: true
instance_class: F1
inbound_services:
  - warmup
handlers:
  - url: /.*
    script: unused
manual_scaling:
  instances: 1
service_account: mystic-column-275402@appspot.gserviceaccount.com